engine/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'helpdesk.views.issues_main_view', {'active_nav': 'my'}, name='index'),
    url(r'^helpdesk/', include('helpdesk.urls', namespace="helpdesk")),
    url(r'^regions/', include('regions.urls', namespace="regions")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('haystack.urls', namespace='search')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

helpdesk/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from helpdesk import views

urlpatterns = patterns('',
    url(r'^$', views.issues_main_view, {'active_nav': 'my'}, name='index'),

    url(r'^(?P<active_nav>(my|all|region|project|service_type|user))'
        '(?:/(?P<item_id>\d+))?(?:/(?P<status>(closed|any)))?(?:/(?P<scope>period))?/$',
        views.issues_main_view, name='issues_main_view'),

     url(r'^my/$', views.issues_main_view, {'active_nav': 'my'}, name='my'),
     url(r'^all/$', views.issues_main_view, {'active_nav': 'all'}, name='all'),

     url(r'^filter/$', views.filter_issues, name='filter'),

    url(r'^issue/(?P<issue_id>\d+)/status/(?P<status_id>\d)/$', views.issue_status, name='issue_status'),
    url(r'^issue/(?P<issue_id>\d+)/edit/$', views.edit_issue, name='edit_issue'),
    url(r'^issue/(?P<issue_id>\d+)/$', views.issue, name='issue'),

    url(r'^new_issue/$', views.new_issue, name='new_issue'),
    url(r'^popover/$', views.popover, name='popover'),
    url(r'^popover/(?P<region_id>\d+)/$', views.popover, name='popover_with_reg'),

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'helpdesk:index'}, name='logout'),
    url(r'^edit_account/$', views.account_change, name='edit_account'),
    url(r'^change_password/$', auth_views.password_change,
        {'template_name': 'registration/change_password.html',
        'post_change_redirect': 'helpdesk:index'},
        name='change_password'),
)

regions/urls.py
from django.conf.urls import patterns, url

from regions import views

urlpatterns = patterns('',
    # ex: /regions/
    url(r'^$', views.index, name='index'),
    # ex: /regions/5/
    url(r'^(?P<region_id>\d+)/$', views.detail, name='detail'),
    url(r'^suggest_region/$', views.suggest_region, name='suggest_region'),
    url(r'^contact/(?P<contact_id>\d+)/edit/$', views.contact_modal, name='contact_edit_modal'),
    url(r'^(?P<region_id>\d+)/new_contact/$', views.contact_modal, name='new_contact_modal'),
)

regions/models.py
# coding: utf-8
from django.db import models


class District(models.Model):
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = u'Федеральные округа'

    name = models.CharField(verbose_name=u'Округ', max_length=128)
    name_short = models.CharField(verbose_name=u'Округ кратко', max_length=128, default='')


class Region(models.Model):
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = u'Регионы'

    region_id = models.IntegerField(verbose_name=u'Номер региона')
    name = models.CharField(verbose_name=u'Регион', max_length=200)
    name_short = models.CharField(verbose_name=u'Регион кратко', max_length=50, blank=True)
    gu = models.TextField(verbose_name=u'ГУ кратко', max_length=200)
    gu_full = models.TextField(verbose_name=u'ГУ полное', max_length=200, blank=True)
    region_count = models.IntegerField(verbose_name=u'Счетчик записей')
    project_name = models.CharField(verbose_name=u'Региональный проект', max_length=100, blank=True)
    gu_dp = models.TextField(verbose_name=u'Дат. падеж кратко', default='', max_length=100, blank=True)
    gu_rp = models.TextField(verbose_name=u'Род. падеж полное', default='', max_length=200, blank=True)
    address_gu = models.TextField(verbose_name=u'Адрес ГУ', max_length=200, blank=True)
    phone_code = models.TextField(verbose_name=u'Телефонный код', max_length=20, blank=True)
    time_zone = models.IntegerField(verbose_name=u'Временная зона', blank=True)
    is_head = models.BooleanField(verbose_name=u'Столица округа', default=False)
    district = models.ForeignKey(District, verbose_name=u'Округ', default=1, null=True)


class Contact(models.Model):
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = u'Контакты'

    name = models.CharField(verbose_name=u'Ф.И.О.', max_length=128)
    phone = models.CharField(verbose_name=u'Телефон', max_length=128, null=True, blank=True)
    email = models.CharField(verbose_name=u'E-mail', max_length=128, null=True, blank=True)
    job = models.CharField(verbose_name=u'Должность', max_length=200, null=True, blank=True)
    region = models.ForeignKey(Region, verbose_name=u'Регион')
    legacy_id = models.IntegerField(verbose_name='MySQL ID', null=True, blank=True)

    @property
    def emails_as_list(self):
        return self.email.replace(';',' ').replace(',',' ').split()

regions/forms.py
from django.forms import ModelForm
from regions.models import Contact


class ContactForm(ModelForm):

    class Meta:
        model = Contact
        fields = ('region', 'name', 'phone', 'email', 'job')

regions/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from regions.models import Region, Contact
from helpdesk.models import Issue
from regions.forms import ContactForm


def index(request):
    region_list = Region.objects.order_by('region_id')
    context = {'region_list': region_list}
    return render(request, 'regions/index.html', context)


def suggest_region(request):
    reg_list = []
    if request.method == 'GET':
        starts_with = request.GET['suggestion']
        if starts_with:
            reg_list = Region.objects.filter(name_short__istartswith=starts_with)
    return render(request, 'regions/nav_list_suggest.html', {'regions': reg_list})


def detail(request, region_id):
    region = get_object_or_404(Region, pk=region_id)
    contact_list = Contact.objects.filter(region=region)
    last_issues = Issue.objects.filter(region=region)[:5]
    context = {'region': region, 'contact_list': contact_list, 'last_issues': last_issues}
    if request.method == 'POST' and ('new_contact' in request.POST or 'edit_contact' in request.POST):
        if 'new_contact' in request.POST:
            context = contact_modal_context(request, context, region_id=request.POST.get('region'))
        elif 'edit_contact' in request.POST:
            context = contact_modal_context(request, context, contact_id=request.POST.get('contact_id'))
        if context['contact_form'].is_valid():
            context['contact_form'].save()

    return render(request, 'regions/detail.html', context)


def contact_modal_context(request, context=None, contact_id=None, region_id=None):
    if context is None:
        context = {}
    if contact_id:
        context['contact_id'] = contact_id
        curr_contact = get_object_or_404(Contact, pk=contact_id)
        context['contact_form'] = ContactForm(request.POST or None, instance=curr_contact)
        context['action'] = 'edit_contact'
    elif region_id:
        initial = {'region': region_id}
        context['contact_form'] = ContactForm(request.POST or None, initial=initial)
        context['action'] = 'new_contact'
    else:
        raise Http404
    return context


def contact_modal(request, contact_id=None, region_id=None):
    context = contact_modal_context(request, contact_id=contact_id, region_id=region_id)
    return render(request, 'regions/contact_form_modal.html', context)

templates/regions/contact_form_modal.html
{% load widget_tweaks %}

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
{% if action %}
		<h4 class="modal-title" id="contactModalLabel">{% if action == 'new_contact' %}Новый контакт{% else %}Редактирование контакта{% endif %}</h4>
	</div>
	<form method="post" action=".">
		{% csrf_token %}
		<div class="modal-body">
			<div class="form-horizontal">
				{% if contact_id %}
					<input type="hidden" name="contact_id" value="{{ contact_id }}">
				{% endif %}
				{% for field in contact_form %}
					<div class="form-group">
						<div class="col-md-3 control-label">
							{{ field.label_tag }}
						</div>
						<div class="col-md-7">
							{% render_field field class="form-control" %}
							{{ field.errors }}
						</div>
					</div>
				{% endfor %}
			</div>
		</div>

		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
			<button type="submit" class="btn btn-primary" name="{{ action }}">Сохранить</button>
		</div>
	</form>
{% else %}
	</div>
	<div class="modal-body">
		<div class="progress progress-striped active">
			<div class="progress-bar" style="width:100%"></div>
		</div>
	</div>
{% endif %}

templates/regions/detail.html
{% extends 'regions/index.html' %}

{% load staticfiles %}

{% block title %}. Регионы. {{ region }} {% endblock %}

{% block header_block %} <h3>{{ region }}</h3> {% endblock %}

{% block body_block %}

<!-- Modal -->
<div class="modal fade" id="ContactModal" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			{% include "regions/contact_form_modal.html" %}
		</div>
	</div>
</div>
<!-- end of Modal -->



<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

<div class="panel panel-default">
	<div class="panel-heading" role="tab" id="headingOne">
		<h4 class="panel-title">
			<a data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Контакты
				<small><span class="glyphicon glyphicon glyphicon-menu-down" aria-hidden="true"></span></small>
			</a>
		</h4>
	</div>
	<div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
		<div class="panel-body">
			{% if contact_form.errors %}
			<div class="col-md-3">
				<div class="alert alert-warning alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<p><span class="glyphicon glyphicon-exclamation-sign"></span> Данные заполнены неверно</p>
					<br />
					<button type="button" class="btn btn-default" data-toggle="modal" data-target="#ContactModal">
						Попробуйте еще раз
					</button>
				</div>
			</div>
			{% endif %}

			{% if contact_list %}
			<table class="table table-hover">
				<thead class="issue-table">
					<tr>
						<th>Ф.И.О.</th>
						<th>Телефон</th>
						<th>E-mail</th>
						<th>Должность</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{% for item in contact_list %}
						<tr>
							<td class="text-nowrap">{{ item.name }}</td>
							<td class="text-nowrap">{{ item.phone }}</td>
							<td>
								{% for email in item.emails_as_list %}
									<a href="mailto:{{ email }}">{{ email }}</a>
								{% endfor %}
							</td>
							<td>{{ item.job }}</td>
							<td><a href="{% url 'regions:contact_edit_modal' item.id %}" data-toggle="modal" data-target="#ContactModal"><span class="glyphicon glyphicon-pencil"></span></a></td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			{% else %}Сохраненных контактов нет
			{% endif %}
			<hr />
			<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#ContactModal"
					href="{% url 'regions:new_contact_modal' region.id %}">
				<span class="glyphicon glyphicon-plus"></span> Новый контакт </button>
		</div>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading" role="tab" id="headingTwo">
		<h4 class="panel-title">
			<a data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">Последние запросы
				<small><span class="glyphicon glyphicon glyphicon-menu-down" aria-hidden="true"></span></small>
			</a>
		</h4>
	</div>
	<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
			{% if last_issues %}
				{% include "helpdesk/table.html" with issues=last_issues %}
			{% endif %}
			<div class="panel-body">
				{% if not last_issues %}Запросы не найдены. {% endif %}
				<a href="{% url 'helpdesk:issues_main_view' 'region' region.id %}">Все запросы</a>
			</div>
	</div>
</div>
</div>
{% endblock %}

templates/regions/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}. Регионы{% endblock %}

{% block side_block %}
	<small>
    <ul class="nav nav-list">
        <li class="nav-header"></li>
        <form>
            <li><input class="search-query span10" type="text" name="suggestion" value="" id="suggestion" placeholder=" Начните вводить имя"/></li>
        </form>
    </ul>

    <div id="suggest_region"></div>

    <hr />

    {% load nav_list_tag %}
    {% regions_list region %}
	</small>
{% endblock %}


{% block header_block %}<h3>Регионы</h3>{% endblock %}


{% block body_block %}<div id="ymap"></div>{% endblock %}


{% block include_block %}
		<script src="http://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
        <script src="{% static "js/ymap.js" %}"></script>

        <script src="{% static "js/regions-ajax.js" %}"></script>
{% endblock %}

templates/regions/nav_list.html
<ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="#district" aria-controls="district" role="tab" data-toggle="tab">По округам</a></li>
        <li role="presentation"><a href="#list" aria-controls="list" role="tab" data-toggle="tab">Списком</a></li>
</ul>

<div class="tab-content">
    <div role="tabpanel" class="tab-pane active fade in" id="district">
        <ul class="nav nav-sidebar">
			{% regroup regions|dictsort:"district.id" by district as district_list %}

			{% for district in district_list %}
				<li>
				   <a data-toggle="collapse"
						href="#district{{ district.grouper.id }}"
						aria-controls="district{{ district.grouper.id }}"
						{% if act_region.district = district.grouper %}
							aria-expanded="true">
						{% else %}
							aria-expanded="false">
						{% endif %}
					{{ district.grouper }}
					</a>
				</li>
				<div role="tabpanel" id="district{{ district.grouper.id }}"
					{% if act_region.district = district.grouper %}
						class="collapse in">
					{% else %}
						class="collapse">
					{% endif %}

					<ul class="nav nav-sidebar-group">
						{% for region in district.list %}
							{% if region = act_region %}
								<li class="active">
							{% else %}
								<li>
							{% endif %}
									<a href="{% url 'regions:detail' region.id %}"><span class="badge">{{ region.region_id }}</span> {{ region }}</a>
								</li>
						{% endfor %}
					</ul>
				</div>
			{% endfor %}

			{% comment %}
            {% if districts %}
                {% for district in districts %}
                    <li>
                       <a data-toggle="collapse"
                            href="#district{{ district.id }}"
                            aria-controls="district{{ district.id }}"
                            {% if act_region.district = district %}
                                aria-expanded="true">
                            {% else %}
                                aria-expanded="false">
                            {% endif %}
                        {{ district }}
                        </a>
                    </li>

                    <div role="tabpanel" id="district{{ district.id }}"
                        {% if act_region.district = district %}
                            class="collapse in">
                        {% else %}
                            class="collapse">
                        {% endif %}

                        <ul class="nav nav-sidebar-group">
                        {% for region in regions %}
                            {% if region.district = district %}
                                {% if region = act_region %}
                                    <li class="active">
                                {% else %}
                                    <li>
                                {% endif %}
                                        <a href="{% url 'regions:detail' region.id %}"><span class="badge">{{ region.region_id }}</span> {{ region }}</a>
                                    </li>
                            {% endif %}
                        {% endfor %}
                        </ul>

                    </div>
                {% endfor %}
            {% endif %}
			{% endcomment %}
        </ul>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="list">
        <ul class="nav nav-sidebar">
            {% if regions %}
                {% for region in regions %}
                    {% if region = act_region %} <li class="active"> {% else %} <li>{% endif %}
                        <a href="{% url 'regions:detail' region.id %}"><span class="badge">{{ region.region_id }}</span> {{ region }}</a></li>
                {% endfor %}
            {% endif %}
        </ul>
    </div>
</div>

templates/regions/nav_list_suggest.html
<ul class="nav nav-sidebar">
    {% if regions %}
        {% for region in regions %}
            <li>
                <a href="{% url 'regions:detail' region.id %}"><span class="badge">{{ region.region_id }}</span> {{ region }}</a>
            </li>
        {% endfor %}
    {% endif %}
</ul>