engine/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'helpdesk.views.issues_main_view', {'active_nav': 'my'}, name='index'),
    url(r'^helpdesk/', include('helpdesk.urls', namespace="helpdesk")),
    url(r'^regions/', include('regions.urls', namespace="regions")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('haystack.urls', namespace='search')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

helpdesk/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from helpdesk import views

urlpatterns = patterns('',
    url(r'^$', views.issues_main_view, {'active_nav': 'my'}, name='index'),

    url(r'^(?P<active_nav>(my|all|region|project|service_type|user))'
        '(?:/(?P<item_id>\d+))?(?:/(?P<status>(closed|any)))?(?:/(?P<scope>period))?/$',
        views.issues_main_view, name='issues_main_view'),

     url(r'^my/$', views.issues_main_view, {'active_nav': 'my'}, name='my'),
     url(r'^all/$', views.issues_main_view, {'active_nav': 'all'}, name='all'),

     url(r'^filter/$', views.filter_issues, name='filter'),

    url(r'^issue/(?P<issue_id>\d+)/status/(?P<status_id>\d)/$', views.issue_status, name='issue_status'),
    url(r'^issue/(?P<issue_id>\d+)/edit/$', views.edit_issue, name='edit_issue'),
    url(r'^issue/(?P<issue_id>\d+)/$', views.issue, name='issue'),

    url(r'^new_issue/$', views.new_issue, name='new_issue'),
    url(r'^popover/$', views.popover, name='popover'),
    url(r'^popover/(?P<region_id>\d+)/$', views.popover, name='popover_with_reg'),

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'helpdesk:index'}, name='logout'),
    url(r'^edit_account/$', views.account_change, name='edit_account'),
    url(r'^change_password/$', auth_views.password_change,
        {'template_name': 'registration/change_password.html',
        'post_change_redirect': 'helpdesk:index'},
        name='change_password'),
)

templates/search/search.html
{% extends 'helpdesk/helpdesk_base.html' %}

{% load widget_tweaks %}

{% block header_block %}<h2>Поиск</h2>{% endblock %}

{% block body_block %}


    <form class="form-horizontal" role="form" method="get" action=".">
		<div class="form-group">
			<div class="col-md-4">
				<div class="input-group">
					{% render_field form.q class="form-control" placeholder="Введите запрос" %}
					<span class="input-group-btn">
						<button class="btn btn-primary" type="submit">Искать</button>
						{{ form.q.errors }}
					</span>
				</div>
			</div>
		</div>

        {% if query %}
            <h4>Результаты поиска</h4>

            {% for result in page.object_list %}
                <p>
		    {% if result.object %}
                        <a href="{% url 'helpdesk:issue' result.object.id %}">{{ result.object }}. {{ result.object.subject }}</a>
		    {% endif %}
                </p>
            {% empty %}
                <p>Ничего не найдено</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div class="col-md-4">
  					<ul class="pager">
                    	{% if page.has_previous %}<li class="previous"><a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">
						{% else %}<li class="previous disabled"><a href="#">{% endif %}
						<span aria-hidden="true">&larr;</span> Пред.</a></li>

                    	{% if page.has_next %}<li class="next"><a href="?q={{ query }}&amp;page={{ page.next_page_number }}">
						{% else %}<li class="next disabled"><a href="#">{% endif %}
						След. <span aria-hidden="true">&rarr;</span></a></li>
					</ul>
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}