engine/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'helpdesk.views.issues_main_view', {'active_nav': 'my'}, name='index'),
    url(r'^helpdesk/', include('helpdesk.urls', namespace="helpdesk")),
    url(r'^regions/', include('regions.urls', namespace="regions")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('haystack.urls', namespace='search')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

helpdesk/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from helpdesk import views

urlpatterns = patterns('',
    url(r'^$', views.issues_main_view, {'active_nav': 'my'}, name='index'),

    url(r'^(?P<active_nav>(my|all|region|project|service_type|user))'
        '(?:/(?P<item_id>\d+))?(?:/(?P<status>(closed|any)))?(?:/(?P<scope>period))?/$',
        views.issues_main_view, name='issues_main_view'),

     url(r'^my/$', views.issues_main_view, {'active_nav': 'my'}, name='my'),
     url(r'^all/$', views.issues_main_view, {'active_nav': 'all'}, name='all'),

     url(r'^filter/$', views.filter_issues, name='filter'),

    url(r'^issue/(?P<issue_id>\d+)/status/(?P<status_id>\d)/$', views.issue_status, name='issue_status'),
    url(r'^issue/(?P<issue_id>\d+)/edit/$', views.edit_issue, name='edit_issue'),
    url(r'^issue/(?P<issue_id>\d+)/$', views.issue, name='issue'),

    url(r'^new_issue/$', views.new_issue, name='new_issue'),
    url(r'^popover/$', views.popover, name='popover'),
    url(r'^popover/(?P<region_id>\d+)/$', views.popover, name='popover_with_reg'),

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'helpdesk:index'}, name='logout'),
    url(r'^edit_account/$', views.account_change, name='edit_account'),
    url(r'^change_password/$', auth_views.password_change,
        {'template_name': 'registration/change_password.html',
        'post_change_redirect': 'helpdesk:index'},
        name='change_password'),
)

regions/urls.py
from django.conf.urls import patterns, url

from regions import views

urlpatterns = patterns('',
    # ex: /regions/
    url(r'^$', views.index, name='index'),
    # ex: /regions/5/
    url(r'^(?P<region_id>\d+)/$', views.detail, name='detail'),
    url(r'^suggest_region/$', views.suggest_region, name='suggest_region'),
    url(r'^contact/(?P<contact_id>\d+)/edit/$', views.contact_modal, name='contact_edit_modal'),
    url(r'^(?P<region_id>\d+)/new_contact/$', views.contact_modal, name='new_contact_modal'),
)

helpdesk/models.py
# coding: utf-8
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from regions.models import Region, Contact
from datetime import date


class Project(models.Model):

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name_short

    class Meta:
        verbose_name = u'проект'
        verbose_name_plural = u'проекты'

    name = models.CharField(verbose_name=u'проект', max_length=128)
    name_short = models.CharField(verbose_name=u'проект кратко', max_length=20)
    common_email = models.EmailField(verbose_name=u'общий e-mail', null=True, blank=True)


class Contract(models.Model):
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name_short

    class Meta:
        verbose_name = u'договор'
        verbose_name_plural = u'договоры'

    name_short = models.CharField(verbose_name=u'краткое имя', max_length=128)
    name = models.CharField(verbose_name=u'имя', max_length=128)
    project = models.ForeignKey(Project, verbose_name=u'связанный проект')
    contract_subject = models.CharField(verbose_name=u'предмет договора', max_length=128)
    contract_id = models.CharField(verbose_name=u'номер договора', max_length=32)
    contract_date = models.DateField(verbose_name=u'дата заключения')
    contract_expires = models.DateField(verbose_name=u'действует до', null=True, blank=True)
    annex_id = models.CharField(verbose_name=u'номер доп. соглашения', max_length=32, null=True, blank=True)
    annex_date = models.DateField(verbose_name=u'дата заключения доп. соглашения', null=True, blank=True)
    comment = models.TextField(verbose_name=u'комментарий', blank=True)


class Status(models.Model):

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'статус'
        verbose_name_plural = u'статусы'

    name = models.CharField(verbose_name=u'статус', max_length=20)


class Priority(models.Model):

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'приоритет'
        verbose_name_plural = u'приоритеты'

    name = models.CharField(verbose_name=u'приоритет', max_length=20)


class Component(models.Model):

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'компонент'
        verbose_name_plural = u'компоненты'

    name = models.CharField(verbose_name=u'компонент', max_length=20)
    project = models.ForeignKey(Project, verbose_name=u'проект', default=4)


class Source(models.Model):

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'источник'
        verbose_name_plural = u'источники'

    name = models.CharField(verbose_name=u'источник', max_length=20)


class ServiceType(models.Model):

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'тип запроса'
        verbose_name_plural = u'типы запросов'

    name = models.CharField(verbose_name=u'тип запроса', max_length=50)
    name_short = models.CharField(verbose_name=u'тип запроса кратко', max_length=20)
    name_full = models.CharField(verbose_name=u'тип услуги по договору', max_length=150)
    project = models.ForeignKey(Project, verbose_name=u'проект', default=4)


class Issue(models.Model):

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.issue_id

    class Meta:
        verbose_name = u'запрос'
        verbose_name_plural = u'запросы'
        ordering = ['-created']

    issue_id = models.CharField(verbose_name=u'номер запроса', max_length=30)
    external_id = models.CharField(verbose_name=u'входящий номер', max_length=50, blank=True)
    subject = models.CharField(verbose_name=u'тема', max_length=255)
    opened = models.DateField(verbose_name=u'дата открытия', null=True)
    created = models.DateTimeField(verbose_name=u'создан', auto_now_add=True)
    changed = models.DateTimeField(verbose_name=u'изменен', auto_now=True)
    priority = models.ForeignKey(Priority, verbose_name=u'приоритет', default=3)
    status = models.ForeignKey(Status, verbose_name=u'статус', default=1)
    project = models.ForeignKey(Project, verbose_name=u'проект', default=4)
    component = models.ForeignKey(Component, verbose_name=u'компонент', null=True, blank=True)
    service_type = models.ForeignKey(ServiceType, verbose_name=u'тип запроса', default=1)
    source = models.ForeignKey(Source, verbose_name=u'источник', null=True, blank=True)
    control = models.DateField(verbose_name=u'дата контроля')
    creator = models.ForeignKey(User, related_name='issues_created', verbose_name=u'автор')
    assignee = models.ForeignKey(User, related_name='issues_assigned', verbose_name=u'ответственный')
    region = models.ForeignKey(Region, verbose_name=u'регион')
    formed = models.BooleanField(verbose_name=u'оформлен', default=False
                                 , help_text=u'Оформлено для отчета')
    contact = models.ForeignKey(Contact, verbose_name=u'контакт', blank=True, null=True)
    description = models.TextField(verbose_name=u'описание', blank=True
                                   , help_text=u'Данная информация не идет в отчет')
    report_description = models.TextField(verbose_name=u'описание для отчета', blank=True
                                          , help_text=u'Краткое описание запрошенной услуги')
    report_solution = models.TextField(verbose_name=u'решение для отчета', blank=True
                                       , help_text=u'Краткое описание содержания оказанной услуги')
    legacy_id = models.IntegerField(verbose_name='mySQL ID', null=True, blank=True)
    contracts = models.ManyToManyField(Contract, verbose_name=u'договор', blank=True)

    @property
    def expired(self):
        return self.control < date.today()

    @property
    def expires(self):
        return self.control >= date.today() and (self.control - date.today()).days <= 1

    @property
    def expires_tomorrow(self):
        return (self.control - date.today()).days == 1

    @property
    def expires_today(self):
        return self.control == date.today()

    @property
    def get_url(self):
        return settings.BASE_URL + reverse('helpdesk:issue', args=[self.id])


class Comment(models.Model):
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.comment_text[:20]

    class Meta:
        verbose_name = u'комментарий'
        verbose_name_plural = u'комментарии'

    comment_text = models.TextField(verbose_name=u'текст комментария')
    author = models.ForeignKey(User, verbose_name=u'автор')
    issue = models.ForeignKey(Issue, verbose_name=u'запрос')
    created = models.DateTimeField(verbose_name=u'создан', auto_now_add=True)
    legacy_id = models.IntegerField(verbose_name='MySQL ID', null=True, blank=True)

regions/models.py
# coding: utf-8
from django.db import models


class District(models.Model):
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = u'Федеральные округа'

    name = models.CharField(verbose_name=u'Округ', max_length=128)
    name_short = models.CharField(verbose_name=u'Округ кратко', max_length=128, default='')


class Region(models.Model):
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = u'Регионы'

    region_id = models.IntegerField(verbose_name=u'Номер региона')
    name = models.CharField(verbose_name=u'Регион', max_length=200)
    name_short = models.CharField(verbose_name=u'Регион кратко', max_length=50, blank=True)
    gu = models.TextField(verbose_name=u'ГУ кратко', max_length=200)
    gu_full = models.TextField(verbose_name=u'ГУ полное', max_length=200, blank=True)
    region_count = models.IntegerField(verbose_name=u'Счетчик записей')
    project_name = models.CharField(verbose_name=u'Региональный проект', max_length=100, blank=True)
    gu_dp = models.TextField(verbose_name=u'Дат. падеж кратко', default='', max_length=100, blank=True)
    gu_rp = models.TextField(verbose_name=u'Род. падеж полное', default='', max_length=200, blank=True)
    address_gu = models.TextField(verbose_name=u'Адрес ГУ', max_length=200, blank=True)
    phone_code = models.TextField(verbose_name=u'Телефонный код', max_length=20, blank=True)
    time_zone = models.IntegerField(verbose_name=u'Временная зона', blank=True)
    is_head = models.BooleanField(verbose_name=u'Столица округа', default=False)
    district = models.ForeignKey(District, verbose_name=u'Округ', default=1, null=True)


class Contact(models.Model):
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = u'Контакты'

    name = models.CharField(verbose_name=u'Ф.И.О.', max_length=128)
    phone = models.CharField(verbose_name=u'Телефон', max_length=128, null=True, blank=True)
    email = models.CharField(verbose_name=u'E-mail', max_length=128, null=True, blank=True)
    job = models.CharField(verbose_name=u'Должность', max_length=200, null=True, blank=True)
    region = models.ForeignKey(Region, verbose_name=u'Регион')
    legacy_id = models.IntegerField(verbose_name='MySQL ID', null=True, blank=True)

    @property
    def emails_as_list(self):
        return self.email.replace(';',' ').replace(',',' ').split()

templates/helpdesk/contact_form_modal.html
{% load widget_tweaks %}

<div class="modal fade" id="newContact" tabindex="-1" role="dialog" aria-labelledby="newContactLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="newContactLabel">Новый контакт</h4>
			</div>
			<div class="modal-body">
				<div class="form-horizontal">
					<div class="form-group">
						<div class="col-md-3 control-label">
							<label>Регион:</label>
						</div>
						<div class="col-md-7">
							<div class="form-control-static" id="modal_region"></div>
						</div>
					</div>
					{% for field in contact_form %}
						{% if field.name != 'region' %}
							<div class="form-group">
								<div class="col-md-3 control-label">
									{{ field.label_tag }}
								</div>
								<div class="col-md-7">
									{% render_field field class="form-control" %}
									{{ field.errors }}
								</div>
							</div>
						{% endif %}
					{% endfor %}
				</div>
			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
				<button type="submit" class="btn btn-primary" name="new_contact">Сохранить</button>
			</div>
		</div>
	</div>
</div>

templates/helpdesk/helpdesk_base.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load quick_filter_tag %}

{% block title %}. Index{% endblock %}

{% block header_block %}{% endblock %}

{% block side_block %}
    <ul class="nav nav-sidebar">
        <li{% if active_nav = 'my' %} class="active" {% endif %}><a href="{% url 'helpdesk:my' %}">Мои запросы</a></li>
        <li{% if active_nav = 'all' %} class="active" {% endif %}><a href="{% url 'helpdesk:all' %}">Все запросы</a></li>

		{% quick_filter_menu active_nav active_item %}

    </ul>
{% endblock %}

{% block header_right_block %}
	<a class="btn btn-primary" href="{% url 'helpdesk:new_issue' %}">
		<span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
		<span class="sr-only">Создать</span>
		Новый запрос
	</a>
	<a class="btn btn-default" href="{% url 'helpdesk:filter' %}">
		<span class="glyphicon glyphicon-filter text-primary" aria-hidden="true"></span>
		<span class="sr-only">Фильтр</span>
		Фильтр
	</a>
	<!--<a class="btn btn-default" href="{% url 'search:haystack_search' %}">
		<span class="glyphicon glyphicon-search text-primary" aria-hidden="true"></span>
		<span class="sr-only">Поиск</span>
		Поиск
	</a>-->
	<a class="btn btn-default" role="button" data-toggle="popover" data-placement="bottom" data-html="true"
			data-content='<form class="form-horizontal" role="form" method="get" action="/search">
				<div class="input-group">
					<input name="q" type="text" class="form-control" placeholder="Введите текст запроса">
					<span class="input-group-btn">
						<button class="btn btn-primary" type="submit">Поиск</button>
					</span>
				</div>
			</form>'>

		<span class="glyphicon glyphicon-search text-primary" aria-hidden="true"></span>
		<span class="sr-only">Поиск</span>
	</a>

{% endblock %}

templates/helpdesk/issue.html
{% extends 'helpdesk/helpdesk_base.html' %}

{% load staticfiles %}

{% load widget_tweaks %}

{% load humanize %}

{% block title %}. Запрос {{ issue.issue_id }} {% endblock %}

{% block header_block %}
	<h4>
		<span class="glyphicon glyphicon-circle-arrow-up
					{% if issue.priority.id == 1 %} text-danger
					{% elif issue.priority.id == 2 %} text-warning
					{% else %} text-success{% endif %}" aria-hidden="true">
		</span>
		<span class="text-info">{{ issue.project }}. {{ issue.issue_id }}{% if issue.external_id %} / {{ issue.external_id }} {% endif %}
		{% if issue.source %}<small>Источник: {{ issue.source }}</small>{% endif %}</span></h4>
	<h3>{{ issue.subject }}</h3>
{% endblock %}

{% block body_block %}

		<div class="row">
			<div class="col-md-9">
				{% if status_message %}
					<div class="alert alert-warning" role="alert">
						{{ status_message }}
					</div>
				{% endif %}
				<div class="panel panel-default">
					<div class="panel-body">
						<p>Тип запроса: {{ issue.service_type }}</p>
						<p>Инициатор:
							<a href="{% url 'regions:detail' issue.region.id %}">
								<span class="badge">{{ issue.region.region_id }}</span>
							{{ issue.region }}</a>{% if issue.contact %},
								{% if issue.contact.phone or issue.contact.email or issue.contact.job %}
									<a href="#" data-toggle="popover" data-placement="right" data-html="true"
									   data-content="
									   {% if issue.contact.phone %}{{ issue.contact.phone }}<br />{% endif %}
									   {% if issue.contact.job %}{{ issue.contact.job }}<br />{% endif %}
									   {% for email in issue.contact.emails_as_list %}
									       <a href='mailto:{{ email }}'>{{ email }}</a><br />
									   {% endfor %}">
										{{ issue.contact.name }}
									</a>
								{% else %}
									{{ issue.contact.name }}
								{% endif %}
							{% endif %}
						</p>
						<p>Компонент: {{ issue.component|default:"нет данных" }}</p>

					</div>
				</div>

				<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="headingOne">

							<h4 class="panel-title">
								<a data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Содержание
									<small><span class="glyphicon glyphicon glyphicon-menu-down" aria-hidden="true"></span></small>
								</a>
							</h4>
						</div>
						<div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
							<div class="panel-body">
								<div class="quick_edit_description" id="content_description">{{ issue.description|linebreaks }}</div>

								<div class="quick_edit_description" style="display: none;">
									<form action="{% url 'helpdesk:issue' issue.id %}" method="post">
										{% csrf_token %}
										<div class="form-group">
											{% render_field description_form.description class="form-control" %}
										</div>
										<button class="btn btn-sm btn-default" name="description_form" type="submit">
											<span class="text-success">
												<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
												<span class="sr-only">Save</span>
											</span>Сохранить
										</button>
										<a href="#!" data-block="description" type="button" class="btn btn-sm btn-default quick_edit" style="display: none;">
											<span class="text-danger">
												<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
												<span class="sr-only">Cancel</span>
											</span>Отменить</a>
									</form>
								</div>
									<small><a href="#!" data-block="description" class="quick_edit">
										<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
										<span class="sr-only">Edit</span>Редактировать
									</a></small>
								<hr />
								{% for comment in issue.comment_set.all %}
										<blockquote>
											<p>{{ comment.comment_text|linebreaks }}</p>
											<footer>{{ comment.author.first_name }} {{ comment.author.last_name }}. {{ comment.created }}</footer>
										</blockquote>
								{% endfor %}
								<form action="{% url 'helpdesk:issue' issue.id %}" method="post">
									{% csrf_token %}
									<div class="form-group">
										{% render_field comment_form.comment_text class="form-control" rows="2" placeholder="Новый комментарий" %}
										{{ comment_form.comment_text.errors }}
									</div>
									<button class="btn btn-default btn-sm" name="comment_form" type="submit">Добавить</button>
								</form>
							</div>
						</div>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="headingThree">
							<h4 class="panel-title">
								{% if issue.formed %}
									<span class="text-success">
										<span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span>
										<span class="sr-only">Formed</span>
									</span>
								{% else %}
									<span class="text-danger">
										<span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span>
										<span class="sr-only">Not formed</span>
									</span>
								{% endif %}
								<a class="collapsed" data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">Данные для отчета
									<small><span class="glyphicon glyphicon glyphicon-menu-down" aria-hidden="true"></span></small>
								</a>
							</h4>
						</div>
						<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
							<div class="panel-body">
								<div class="quick_edit_report" id="content_report">
										<h4>Описание</h4>
									{% if issue.report_description %}
										<p>{{ issue.report_description|linebreaks }}</p>
									{% else %}
										<p>Не заполнено</p>
									{% endif %}
									<hr />
										<h4>Решение</h4>
									{% if issue.report_solution %}
										<p>{{ issue.report_solution|linebreaks }}</p>
									{% else %}
										<p>Не заполнено</p>
									{% endif %}
									<hr />
										<h4>Договор сопровождения</h4>
									{% if issue.contracts.all %}
										<p>{{ issue.contracts.all|join:", " }}</p>
									{% else %}
										<p>Не заполнено</p>
									{% endif %}
									<hr />
								</div>
								<div class="quick_edit_report" style="display: none;">
									<form action="{% url 'helpdesk:issue' issue.id %}" method="post">
										{% csrf_token %}
										<div class="form-group">
											<h4>Описание</h4>
											{% render_field report_form.report_description class="form-control" placeholder=report_form.report_description.help_text %}
										</div>
										<div class="form-group">
											<h4>Решение</h4>
											{% render_field report_form.report_solution class="form-control" placeholder=report_form.report_solution.help_text %}
										</div>
										<div class="form-group">
											<h4>Договор сопровождения</h4>
											{% for contract in report_form.contracts %}
												<label for="{{ contract.id_for_label }}" class="checkbox-inline">
													{{ contract.tag }}{{ contract.choice_label }}
												</label>
											{% endfor %}
											<hr />
										</div>
										<div class="checkbox">
											<label>
												{{ report_form.formed }} {{ report_form.formed.help_text }}
											</label>
										</div>
										<button class="btn btn-sm btn-default" name="report_form" type="submit">
											<span class="text-success">
												<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
												<span class="sr-only">Save</span>
											</span>Сохранить
										</button>
										<a href="#!" data-block="report" type="button" class="btn btn-sm btn-default quick_edit" style="display: none;">
											<span class="text-danger">
												<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
												<span class="sr-only">Cancel</span>
											</span>Отменить</a>
									</form>
								</div>
								<small><a href="#!" data-block="report" class="quick_edit">
									<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
									<span class="sr-only">Edit</span>Редактировать
								</a></small>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-3">
				<ul class="list-group">
					<li class="list-group-item">
						<h4>Статус:
								<span>
									<div class="btn-group">
										<button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
											{{ issue.status }} <span class="caret"></span>
										</button>
										<ul class="dropdown-menu" role="menu">
											{% for status in status_list %}
												{% if status == issue.status %}
													<li class="disabled"><a href="#!">
												{% else %}
													<li><a href="{% url 'helpdesk:issue_status' issue.id status.id %}">
												{% endif %}
														{{ status }}</a></li>
											{% endfor %}
										</ul>
									</div>
								</span>
						</h4>
						<h4>
						Контроль:
							<span class="quick_edit_control">{{ issue.control|date:"d M Y" }}
								<small><a href="#!" data-block="control" class="quick_edit">
										<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
										<span class="sr-only">Edit</span>
								</a></small>{{ control_form.control.errors }}
							</span>
							<span class="quick_edit_control" style="display: none;">
								<form action="{% url 'helpdesk:issue' issue.id %}" method="post">
									{% csrf_token %}
									<div class="input-group input-group-sm">
										{% render_field control_form.control class="form-control input-sm datepicker" %}

										<span class="input-group-btn">
											<button href="#!" data-block="control" type="button" class="btn btn-sm btn-default quick_edit" style="display: none;">
												<span class="text-danger">
													<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
													<span class="sr-only">No</span>
												</span>
											</button>

											<button class="btn btn-sm btn-default" type="submit" name="control_form">
												<span class="text-success">
													<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
													<span class="sr-only">Ok</span>
												</span>
											</button>

										</span>
									</div>
								</form>
							</span>
						</h4>
						{% if issue.expired and issue.status.id != 4 %}
							<div class="alert alert-danger" role="alert">
								<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>&nbsp;Срок контроля истек</div>
						{% endif %}
						{% if issue.expires and not issue.expired and issue.status.id != 4 %}
							<div class="alert alert-warning" role="alert">
								<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>&nbsp;Срок контроля {{ issue.control|naturalday }}</div>
						{% endif %}
					</li>
					<li class="list-group-item">
						<p>Ответственный: {{ issue.assignee.first_name}} {{issue.assignee.last_name}}</p>
						<p>Автор: {{ issue.creator.first_name}} {{issue.creator.last_name}}</p>
					</li>
					<li class="list-group-item">
						<p>Открыт: {{ issue.opened }}</p>
						<p><small>Создан: {{ issue.created }}</small></p>
						{% ifnotequal issue.created|date:"dMYHis" issue.changed|date:"dMYHis" %}
							<p><small>Изменен: {{ issue.changed }}</small></p>
						{% endifnotequal %}
					</li>
					<li class="list-group-item">
						<a class="btn btn-primary" href="{% url 'helpdesk:edit_issue' issue.id %}" role="button">
							<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
							<span class="sr-only">Edit</span>Редактировать запрос</a>
						<!-- <p><a href="#!">Отслеживать</a></p> -->
					</li>
				</ul>
			</div>
		</div>
{% endblock %}

templates/helpdesk/popover.html
{% if region %}
		{% for contact in region.contact_set.all %}
			<p><a href=# class="contact_picker" data-contact="{{ contact.id }}">{{ contact.name }}</a></p>
		{% empty %}
			<p>Список контактов пуст</p>
		{% endfor %}
{% else %}
		Необходимо выбрать инициатора
{% endif %}