engine/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'helpdesk.views.issues_main_view', {'active_nav': 'my'}, name='index'),
    url(r'^helpdesk/', include('helpdesk.urls', namespace="helpdesk")),
    url(r'^regions/', include('regions.urls', namespace="regions")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('haystack.urls', namespace='search')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

helpdesk/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from helpdesk import views

urlpatterns = patterns('',
    url(r'^$', views.issues_main_view, {'active_nav': 'my'}, name='index'),

    url(r'^(?P<active_nav>(my|all|region|project|service_type|user))'
        '(?:/(?P<item_id>\d+))?(?:/(?P<status>(closed|any)))?(?:/(?P<scope>period))?/$',
        views.issues_main_view, name='issues_main_view'),

     url(r'^my/$', views.issues_main_view, {'active_nav': 'my'}, name='my'),
     url(r'^all/$', views.issues_main_view, {'active_nav': 'all'}, name='all'),

     url(r'^filter/$', views.filter_issues, name='filter'),

    url(r'^issue/(?P<issue_id>\d+)/status/(?P<status_id>\d)/$', views.issue_status, name='issue_status'),
    url(r'^issue/(?P<issue_id>\d+)/edit/$', views.edit_issue, name='edit_issue'),
    url(r'^issue/(?P<issue_id>\d+)/$', views.issue, name='issue'),

    url(r'^new_issue/$', views.new_issue, name='new_issue'),
    url(r'^popover/$', views.popover, name='popover'),
    url(r'^popover/(?P<region_id>\d+)/$', views.popover, name='popover_with_reg'),

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'helpdesk:index'}, name='logout'),
    url(r'^edit_account/$', views.account_change, name='edit_account'),
    url(r'^change_password/$', auth_views.password_change,
        {'template_name': 'registration/change_password.html',
        'post_change_redirect': 'helpdesk:index'},
        name='change_password'),
)

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
    {% load staticfiles %}

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
        <link href="{% static "css/dashboard.css" %}" rel="stylesheet" media="screen">
		<link href="{% static "css/datepicker3.css" %}" rel="stylesheet" media="screen">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />

        <title>HelpDesk{% block title %}{% endblock %}</title>
	</head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
				{% block logo_block %}
                <div class="navbar-header">

                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
					<a class="pull-left" style="margin-left: -15px; margin-right: 10px;" href="{% url 'helpdesk:index' %}">
        				<img alt="Factor-TS" src="{% static "images/factor_logo.png" %}"></a>
					<span class="navbar-brand"><span class="text-danger glyphicon glyphicon-fire"></span> Helpdesk</span>

                </div>
				{% endblock %}
				{% block top_nav_block %}
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'helpdesk:index' %}">Запросы</a></li>
                        <li><a href="{% url 'regions:index' %}">Регионы</a></li>
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a id="drop" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
								<span class="sr-only">User</span>
                                <div class="caret"></div>
                            </a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="drop">
                        		<li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'helpdesk:edit_account' %}">Ваши данные</a></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'helpdesk:change_password' %}">Сменить пароль</a></li>
                                <li role="presentation" class="divider"></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'helpdesk:logout' %}">Выход</a></li>
                            </ul>

                        </li>
                    {% else %}
                        <li><a href="{% url 'helpdesk:login' %}">Вход</a></li>
                    {% endif %}
                    </ul>
                </div>
				{% endblock %}
            </div>
        </div>


        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    {% block side_block %}
                    {% endblock %}
                 </div>

                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <div class="pull-right form-inline">
							{% block header_right_block %}{% endblock %}
					</div>
					<div class="page-header">
                        {% block header_block %}{% endblock %}
                    </div>
                    <div>
                        {% block body_block %}{% endblock %}
                    </div>
                </div>

            </div>
        </div>


        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src='{% static "js/bootstrap.min.js" %}'></script>


		{% block include_block %}{% endblock %}
		<script src="{% static "js/bootstrap-datepicker.js" %}"></script>
		<script src="{% static "js/locales/bootstrap-datepicker.ru.js" %}" charset="utf-8"></script>
		<script src="{% static "js/jquery.autosize.min.js" %}"></script>
		<script src="{% static "js/helpdesk.js" %}"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>


    </body>
</html>